### ISSUE TITLE
Gamepad Controller Problemwith context menu

### ISSUE THREAD

**Issue by lapochka8** [ChobitsCrazy/BetterSorting#69]
Have 2 players attempting to use gamepads while playing on the server. They receive this error and get locked out of the context menu. We have tracked the issue down to this mod.
Here is the error log. 
function: doContextOnJoypadSelected -- file: ISInventoryPane.lua line # 1399 | Vanilla
function: onJoypadDown -- file: ISInventoryPage.lua line # 674 | Vanilla
function: onPressButton -- file: JoyPadSetup.lua line # 345 | Vanilla
function: update -- file: JoyPadSetup.lua line # 779 | Vanilla
function: onJoypadRenderTick -- file: JoyPadSetup.lua line # 796 | Vanilla
java.lang.RuntimeException: attempted index of non-table
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaUtil.luaAssert(KahluaUtil.java:70)
    at se.krka.kahlua.vm.KahluaThread.tableSet(KahluaThread.java:1726)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:594)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:65)
    at zombie.GameWindow.frameStep(GameWindow.java:778)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Franisz** [comment]
BetterSorting doesn't touch context menu, I suggest checking other installed mods or attach entire console log file, not just the error.
